name: Mirroring

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
  FILES: "my_marvin.yml,job_dsl.groovy"

jobs:
  check_requiered_files:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: check_presence_of_pushed_FILES
        run: |
          if [ -f "$FILES" ]; then
            echo "No files to check"
            exit 0
          fi
          for file in $FILES; do
            if [ -f $file ]; then
              echo "File $file is pushed! GOOD!!!"
            else
              echo "File $file is not pushed! BAD!!!"
              exit 1
            fi
          done


  push_to_mirror:
    if: github.ref == 'refs/heads/main'
    needs: [check_requiered_files]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
